# Generated by Django 4.1.1 on 2022-09-26 20:56

from django.db import migrations


def forwards(apps, schema_editor):
    try:
        OldModel = apps.get_model("mainapp", "News")
    except LookupError:
        # The old app isn't installed.
        return

    NewModel = apps.get_model("mainapp", "TempNews")
    NewModel.objects.bulk_create(
        NewModel(
            title=old_object.title,
            body=old_object.body,
            preambule=old_object.preambule,
            body_as_markdown=old_object.body_as_markdown,
            deleted=old_object.deleted,
            created=old_object.created,
            updated=old_object.updated,
        )
        for old_object in OldModel.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

    dependencies = [
        ("mainapp", "0003_CreateTempTable"),
    ]
