# Generated by Django 4.1.1 on 2022-09-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_CopyDataToTempTable"),
    ]

    def forward_func(apps, schema_editor):
        # Get model
        News = apps.get_model("mainapp", "News")
        # Delete objects
        News.objects.all().delete()

    operations = [
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
