# Generated by Django 4.1.1 on 2022-09-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_CopyDataToNewsTable"),
    ]

    operations = [migrations.DeleteModel(name="TempNews")]
