# Generated by Django 4.1.1 on 2022-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_courseteachers_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coursefeedback",
            constraint=models.UniqueConstraint(fields=("course", "user"), name="course_user_unique"),
        ),
    ]
