# Generated by Django 4.1.1 on 2022-10-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_coursefeedback_course_user_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
    ]
